name = "lyricpost"
compatibility_date = "2023-05-18"
route = { pattern = "/api/*", zone_name = "lyricpost.sigterm.vodka" }

[vars]
SPOTIFY_CLIENT_ID = "your-client-id-placeholder"
SPOTIFY_CLIENT_SECRET = "your-client-secret-placeholder"